### ISSUE TITLE
Consider extracting the rpm feature as their own library?

### ISSUE THREAD

**Issue by pombredanne** [facebookincubator/fs_image#22]
Have you considered extracting the rpm feature as their own library?
https://github.com/facebookincubator/fs_image/tree/master/fs_image/rpm
these would be quite useful of their own, even outside Buck/Bazel

**Comment by zeroxoneb** [comment]
We haven't considered this too deeply at this stage of the project.  That submodule is purpose built to provide core functionality for the image build tooling, while it might be useful externally, we haven't spent the necessary time/effort to do so. 

Having said that, this project is still quite young and we do intend to eventually add support for other package managers, which at some point in the future might warrant splitting this out.  Thank you!
